In [1]:
import numpy as np

Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [20]:
# a) Диагональная, ортогональная, но не единичная(!)
m = np.diag([1,-1])

AT = m.T
m.dot(AT)


array([[1, 0],
       [0, 1]])

In [57]:
# b,c) Верхнетреугольная, нижнетреугольная,ортогональная
m1 = np.array([[1,0,0],[0,1,0], [0,0,-1]])

AT = m1.T

m1.dot(AT)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [75]:
# d) Матрица, у которой определитель = 1, и все элементы не равны 0
from numpy import linalg
m2 = np.array([[1,2,2],[1,3,2], [1,2,3]])

linalg.det(m2)

1.0

In [77]:
# Найдите собственные значения и собственные вектора матриц:

m3 = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [79]:
w,v = linalg.eig(m3)

In [82]:
# Собственные числа матрицы
w

array([1., 4.])

In [83]:
# Собственные векторы матрицы
v

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [84]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]
